### PR TITLE
Vasilis

### PR DESCRIPTION
**Pull request by giannokostas**

### CODE REVIEW

**Comment by jimdowling** [comment]
Can you change the spark and hadoop versions here? Spark is now 1.6.1. Hadoop is 2.4.0 (that's what we call it, even if you helped upgrade it to 2.5.0).

**Comment by giannokostas** [comment]
I changed the version of spark and hadoop at compile.conf file

**Comment by jimdowling** [comment]
There's conflicts. Can you fix them?

**Comment by giannokostas** [comment]
I did another PR by mistake (with name "merge from upstream/master")

The "fix conflicts" solves the conflicts (a slight change at compile.sh)

**Pull request merged**
